const DRINK_SIZES = {
  s: { size: "200 ml", addPrice: 0 },
  m: { size: "300 ml", addPrice: 0.5 },
  l: { size: "400 ml", addPrice: 1 },
};

const DESSERT_SIZES = {
  s: { size: "50 g", addPrice: 0 },
  m: { size: "100 g", addPrice: 1.5 },
  l: { size: "200 g", addPrice: 3 },
};

const ADDITIVES_COFFEE = [
  { name: "Sugar", addPrice: 0.3 },
  { name: "Cinnamon", addPrice: 0.4 },
  { name: "Syrup", addPrice: 0.5 },
];

const ADDITIVES_TEA = [
  { name: "Sugar", addPrice: 0.3 },
  { name: "Lemon", addPrice: 0.4 },
  { name: "Syrup", addPrice: 0.5 },
];

const ADDITIVES_DESSERT = [
  { name: "Berries", addPrice: 0.5 },
  { name: "Nuts", addPrice: 0.5 },
  { name: "Jam", addPrice: 0.4 },
];

const PRODUCTS = [
  {
    id: "coffee-1",
    category: "coffee",
    name: "Irish coffee",
    description: "Fragrant black coffee with Jameson Irish whiskey and whipped milk",
    price: 7.0,
    image: "img/coffee-1.jpg",
    sizes: DRINK_SIZES,
    additives: ADDITIVES_COFFEE,
  },
  {
    id: "coffee-2",
    category: "coffee",
    name: "Kahlua coffee",
    description: "Classic coffee with milk and Kahlua liqueur under a cap of frothed milk",
    price: 7.0,
    image: "img/coffee-2.jpg",
    sizes: DRINK_SIZES,
    additives: ADDITIVES_COFFEE,
  },
  {
    id: "coffee-3",
    category: "coffee",
    name: "Honey raf",
    description: "Espresso with frothed milk, cream and aromatic honey",
    price: 5.5,
    image: "img/coffee-3.jpg",
    sizes: DRINK_SIZES,
    additives: ADDITIVES_COFFEE,
  },
  {
    id: "coffee-4",
    category: "coffee",
    name: "Ice cappuccino",
    description: "Cappuccino with soft thick foam in summer version with ice",
    price: 5.0,
    image: "img/coffee-4.jpg",
    sizes: DRINK_SIZES,
    additives: ADDITIVES_COFFEE,
  },
  {
    id: "coffee-5",
    category: "coffee",
    name: "Espresso",
    description: "Classic black coffee",
    price: 4.5,
    image: "img/coffee-5.jpg",
    sizes: DRINK_SIZES,
    additives: ADDITIVES_COFFEE,
  },
  {
    id: "coffee-6",
    category: "coffee",
    name: "Latte",
    description: "Espresso coffee with the addition of steamed milk and dense milk foam",
    price: 5.5,
    image: "img/coffee-6.jpg",
    sizes: DRINK_SIZES,
    additives: ADDITIVES_COFFEE,
  },
  {
    id: "coffee-7",
    category: "coffee",
    name: "Latte macchiato",
    description: "Espresso with frothed milk and chocolate",
    price: 5.5,
    image: "img/coffee-7.jpg",
    sizes: DRINK_SIZES,
    additives: ADDITIVES_COFFEE,
  },
  {
    id: "coffee-8",
    category: "coffee",
    name: "Coffee with cognac",
    description: "Fragrant black coffee with cognac and whipped cream",
    price: 6.5,
    image: "img/coffee-8.jpg",
    sizes: DRINK_SIZES,
    additives: ADDITIVES_COFFEE,
  },

  {
    id: "tea-1",
    category: "tea",
    name: "Moroccan",
    description:
      "Fragrant black tea with the addition of tangerine, cinnamon, honey, lemon and mint",
    price: 4.5,
    image: "img/tea-1.png",
    sizes: DRINK_SIZES,
    additives: ADDITIVES_TEA,
  },
  {
    id: "tea-2",
    category: "tea",
    name: "Ginger",
    description: "Original black tea with fresh ginger, lemon and honey",
    price: 5.0,
    image: "img/tea-2.png",
    sizes: DRINK_SIZES,
    additives: ADDITIVES_TEA,
  },
  {
    id: "tea-3",
    category: "tea",
    name: "Cranberry",
    description: "Invigorating black tea with cranberry and honey",
    price: 5.0,
    image: "img/tea-3.png",
    sizes: DRINK_SIZES,
    additives: ADDITIVES_TEA,
  },
  {
    id: "tea-4",
    category: "tea",
    name: "Sea buckthorn",
    description: "Toning sweet black tea with sea buckthorn, fresh thyme and cinnamon",
    price: 5.5,
    image: "img/tea-4.png",
    sizes: DRINK_SIZES,
    additives: ADDITIVES_TEA,
  },

  {
    id: "dessert-1",
    category: "dessert",
    name: "Marble cheesecake",
    description: "Philadelphia cheese with lemon zest on a light sponge cake and red currant jam",
    price: 3.5,
    image: "img/dessert-1.png",
    sizes: DESSERT_SIZES,
    additives: ADDITIVES_DESSERT,
  },
  {
    id: "dessert-2",
    category: "dessert",
    name: "Red velvet",
    description: "Layer cake with cream cheese frosting",
    price: 4.0,
    image: "img/dessert-2.png",
    sizes: DESSERT_SIZES,
    additives: ADDITIVES_DESSERT,
  },
  {
    id: "dessert-3",
    category: "dessert",
    name: "Cheesecakes",
    description:
      "Soft cottage cheese pancakes with sour cream and fresh berries and sprinkled with powdered sugar",
    price: 4.5,
    image: "img/dessert-3.png",
    sizes: DESSERT_SIZES,
    additives: ADDITIVES_DESSERT,
  },
  {
    id: "dessert-4",
    category: "dessert",
    name: "Creme brulee",
    description: "Delicate creamy dessert in a caramel basket with wild berries",
    price: 4.0,
    image: "img/dessert-4.png",
    sizes: DESSERT_SIZES,
    additives: ADDITIVES_DESSERT,
  },
  {
    id: "dessert-5",
    category: "dessert",
    name: "Apple pie",
    description: "Warm spiced apple filling in a crisp crust",
    price: 5.5,
    image: "img/dessert-5.png",
    sizes: DESSERT_SIZES,
    additives: ADDITIVES_DESSERT,
  },
  {
    id: "dessert-6",
    category: "dessert",
    name: "Macarons",
    description: "A trio of delicate almond meringue macarons",
    price: 4.5,
    image: "img/dessert-6.png",
    sizes: DESSERT_SIZES,
    additives: ADDITIVES_DESSERT,
  },
  {
    id: "dessert-7",
    category: "dessert",
    name: "Muffin",
    description: "Soft muffin with chocolate chips",
    price: 3.0,
    image: "img/dessert-7.png",
    sizes: DESSERT_SIZES,
    additives: ADDITIVES_DESSERT,
  },
  {
    id: "dessert-8",
    category: "dessert",
    name: "Cinnamon roll",
    description: "Soft roll swirled with cinnamon and glaze",
    price: 4.0,
    image: "img/dessert-8.png",
    sizes: DESSERT_SIZES,
    additives: ADDITIVES_DESSERT,
  },
];
